:- module(tax_api, [tax_calculate/1, tax_brackets_table_html/3, tax_bracket_rows_html/2, results_content//5, tax_response_html//3]).

:- use_module(library(http/http_parameters)).
:- use_module(library(http/http_json)).
:- use_module(library(http/html_write)).
:- use_module('../lib/tax').
:- use_module('../components/ui').

% Format currency with 2 decimal places
format_currency(Value, Formatted) :-
    format(string(NumStr), '~2f', [Value]),
    string_concat('€', NumStr, Formatted).

tax_calculate(Request) :-
    http_parameters(Request, [
        gross(Gross, [number]),
        tax_class(TaxClass, [default('1')])
    ]),
    calculate_tax(Gross, _Tax, _Net, Details),
    phrase(tax_response_html(Gross, TaxClass, Details), HTMLTokens),
    format('Content-type: text/html~n~n'),
    print_html(HTMLTokens).

% tax_response_html//3: DCG rule generating the #tax-calculator-container div
tax_response_html(Gross, TaxClass, json([gross=GrossResult, tax=Tax, social_security=SocialSecurity, net=Net, tax_brackets=TaxBrackets])) -->
    {
        format_currency(GrossResult, GrossF),
        format_currency(Tax, TaxF),
        format_currency(SocialSecurity, SocialSecurityF),
        format_currency(Net, NetF),
        tax_brackets_table_html(TaxBrackets, TaxBracketsHTML, []),
        ResultsTerm = tax_api:results_content(GrossF, TaxF, SocialSecurityF, NetF, TaxBracketsHTML)
    },
    % Directly call the ui:tax_calculator_container DCG rule.
    % Its expansion (the div with id='tax-calculator-container') becomes the content generated by this DCG rule.
    ui:tax_calculator_container(Gross, TaxClass, ResultsTerm).

% DCG rule for results content. It will be called as tax_api:results_content by render_results//1 in ui.pl
results_content(GrossF, TaxF, SocialSecurityF, NetF, TaxBracketsHTML) -->
    html([
        table([class('w-full mb-4')], [
            tbody([],
                [
                    tr([], [
                        td([class('font-medium')], 'Gross Salary:'),
                        td([class('text-right')], [GrossF])
                    ]),
                    tr([], [
                        td([class('font-medium')], 'Income Tax:'),
                        td([class('text-right')], [TaxF])
                    ]),
                    tr([], [
                        td([class('font-medium')], 'Social Security:'),
                        td([class('text-right')], [SocialSecurityF])
                    ]),
                    tr([class('border-t border-gray-200 font-semibold')], [
                        td([], 'Net Salary:'),
                        td([class('text-right')], [NetF])
                    ])
                ])
        ]),
        h4([class('text-md font-semibold mt-4 mb-2')], 'Tax Brackets Breakdown'),
        div([class('text-sm')], [TaxBracketsHTML])
    ]).

% Generate tax brackets table HTML
tax_brackets_table_html(Brackets, HTML, []) :-
    tax_bracket_rows_html(Brackets, RowsHTML),
    HTML = table([class('w-full text-xs')], [
        thead([],
            [tr([class('bg-gray-100')], [
                th([class('text-left py-1')], ['Bracket']),
                th([class('text-center py-1')], ['Rate']),
                th([class('text-right py-1')], ['Amount'])
            ])
        ]),
        tbody([], RowsHTML)
    ]).

% Generate rows for tax brackets
tax_bracket_rows_html([], []).
tax_bracket_rows_html([json([min=Min, max=Max, rate=Rate, amount=Amount])|Rest], [Row|RestRows]) :-
    format_currency(Min, MinF),
    format_currency(Max, MaxF),
    format_currency(Amount, AmountF),
    Row = tr([class('border-t border-gray-100')], [
        td([class('py-1')], [MinF, ' - ', MaxF]),
        td([class('text-center py-1')], [Rate, '%']),
        td([class('text-right py-1')], [AmountF])
    ]),
    tax_bracket_rows_html(Rest, RestRows).
