:- module(tax_api, [tax_calculate/1, deductions_table_html/3, results_content//6, tax_response_html//3]).

:- use_module(library(http/http_parameters)).
:- use_module(library(http/http_json)).
:- use_module(library(http/html_write)).
:- use_module('../lib/tax').
:- use_module('../components/ui').

% Format currency with 2 decimal places
format_currency(Value, Formatted) :-
    format(string(NumStr), '~2f', [Value]),
    string_concat('€', NumStr, Formatted).

tax_calculate(Request) :-
    http_parameters(Request, [
        gross(Gross, [number]),
        tax_class(TaxClass, [default('1')])
    ]),
    calculate_tax(Gross, _Tax, _Net, Details),
    phrase(tax_response_html(Gross, TaxClass, Details), HTMLTokens),
    format('Content-type: text/html~n~n'),
    print_html(HTMLTokens).

% tax_response_html//3: DCG rule generating the #tax-calculator-container div
tax_response_html(Gross, TaxClass, json([gross=GrossResult, tax=Tax, social_contribution=SocialContribution, net=Net, taxed_income=TaxedIncome, deductions=Deductions])) -->
    {
        format_currency(GrossResult, GrossF),
        format_currency(Tax, TaxF),
        format_currency(SocialContribution, SocialContributionF),
        format_currency(Net, NetF),
        format_currency(TaxedIncome, TaxedIncomeF),
        deductions_table_html(Deductions, DeductionsHTML, []),
        ResultsTerm = tax_api:results_content(GrossF, TaxF, SocialContributionF, NetF, TaxedIncomeF, DeductionsHTML)
    },
    % Directly call the ui:tax_calculator_container DCG rule.
    % Its expansion (the div with id='tax-calculator-container') becomes the content generated by this DCG rule.
    ui:tax_calculator_container(Gross, TaxClass, ResultsTerm).

% DCG rule for results content. It will be called as tax_api:results_content by render_results//1 in ui.pl
results_content(GrossF, TaxF, SocialContributionF, NetF, TaxedIncomeF, DeductionsHTML) -->
    html([
        table([class('w-full mb-4')], [
            tbody([],
                [
                    tr([], [
                        td([class('font-medium')], 'Gross Salary:'),
                        td([class('text-right')], [GrossF])
                    ]),
                    tr([], [
                        td([class('font-medium')], 'Taxed Income:'),
                        td([class('text-right')], [TaxedIncomeF])
                    ]),
                    tr([], [
                        td([class('font-medium')], 'Income Tax:'),
                        td([class('text-right')], [TaxF])
                    ]),
                    tr([], [
                        td([class('font-medium')], 'Social Contributions:'),
                        td([class('text-right')], [SocialContributionF])
                    ]),
                    tr([class('border-t border-gray-200 font-semibold')], [
                        td([], 'Net Salary:'),
                        td([class('text-right')], [NetF])
                    ])
                ])
        ]),
        h4([class('text-md font-semibold mt-4 mb-2')], 'Deductions Breakdown'),
        div([class('text-sm')], [DeductionsHTML])
    ]).

% Generate deductions table HTML
deductions_table_html(json([healthcare=Healthcare, healthcare_contrib=HealthcareContrib, pension=Pension, unemployment=Unemployment]), HTML, []) :-
    format_currency(Healthcare, HealthcareF),
    format_currency(HealthcareContrib, HealthcareContribF),
    format_currency(Pension, PensionF),
    format_currency(Unemployment, UnemploymentF),
    HTML = table([class('w-full text-xs')], [
        thead([],
            [tr([class('bg-gray-100')], [
                th([class('text-left py-1')], ['Deduction Type']),
                th([class('text-right py-1')], ['Amount'])
            ])
        ]),
        tbody([], [
            tr([class('border-t border-gray-100')], [
                td([class('py-1')], 'Healthcare (2.8%)'),
                td([class('text-right py-1')], [HealthcareF])
            ]),
            tr([class('border-t border-gray-100')], [
                td([class('py-1')], 'Healthcare Contribution (0.25%)'),
                td([class('text-right py-1')], [HealthcareContribF])
            ]),
            tr([class('border-t border-gray-100')], [
                td([class('py-1')], 'Pension (8%)'),
                td([class('text-right py-1')], [PensionF])
            ]),
            tr([class('border-t border-gray-100')], [
                td([class('py-1')], 'Unemployment (1.4%)'),
                td([class('text-right py-1')], [UnemploymentF])
            ])
        ])
    ]).
